export default {
  singin: "qm/sign-in",
  reserve: "qm/reserveque",
  getque: "qm/reserveorder",
  getmenu: "qm/getfoods",
  userDetail: "qm/getusers",
  getOrderDetail: "qm/getorder",
  getQueDetail: "qm/getque",
  uploadPayslip: "qm/uploadpayslip",
  uploadAmount: "qm/updateamount",
  adminTable: "qm/getallque",
  updateStatus: "qm/updatestatus",
  postEvent: "qm/createevent",
  getEvent: "qm/getevent",
  deleteEvent: "qm/deleteevent",
}
